name: Set Milestone on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  set-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Get main version name
        id: get-main-version-name
        run: |
          # file_path="build-logic/convention/src/main/java/config/MusinsaConfig.kt"  # 파일 경로 지정
          # main_version=$(git show origin/main:$file_path | grep 'VERSION_NAME' | cut -d'=' -f2 | tr -d ' ')
          main_version="1.1.0"
          echo "Main version : $main_version"
          echo "VERSION_NAME=$main_version" >> $GITHUB_ENV

      - name: Get milestone ID by name
        id: get-milestone-id
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: milestones } = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const versionName = process.env.VERSION_NAME;
            const milestone = milestones.find(m => m.title === versionName); // Replace with your milestone name
            if (milestone) {
              core.setOutput('milestoneId', milestone.number);
            } else {
              core.setFailed('Milestone not found.');
            }

      - name: Set milestone
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              milestone: ${{ steps.get-milestone-id.outputs.milestoneId }}
            })